# Generated by Django 4.0.5 on 2022-06-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('img', models.CharField(max_length=128, verbose_name='图像')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=32, verbose_name='商品名'),
        ),
    ]
