# Generated by Django 4.0.5 on 2022-06-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_rename_age_city_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='KQ_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=32, verbose_name='项目编号')),
                ('item_name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('task_number', models.CharField(max_length=32, verbose_name='任务编号')),
                ('task_name', models.CharField(max_length=64, verbose_name='任务名称')),
                ('report_task_num', models.CharField(max_length=32, verbose_name='项目编号')),
                ('task_proportion', models.FloatField(verbose_name='任务占比')),
                ('reporter_depart', models.CharField(max_length=64, verbose_name='汇报人部门')),
                ('reporter_number', models.CharField(max_length=32, verbose_name='汇报人编号')),
                ('reporter_name', models.CharField(max_length=32, verbose_name='汇报人姓名')),
                ('report_date', models.DateField(verbose_name='汇报日期')),
                ('report_task_date', models.DateField(verbose_name='报工日期')),
                ('work_detail', models.TextField(verbose_name='工作内容')),
                ('workload', models.CharField(max_length=32, verbose_name='当日投入工作量')),
                ('auditor_number', models.CharField(max_length=32, verbose_name='审核人编号')),
                ('auditor', models.CharField(max_length=32, verbose_name='审核人')),
                ('audit_completion_rate', models.CharField(max_length=32, verbose_name='审核完成率')),
                ('audit_result', models.CharField(max_length=32, verbose_name='审核结果')),
                ('get_your_work_done_today', models.CharField(max_length=32, verbose_name='今日完成工作量')),
                ('way_to_report_work', models.CharField(max_length=32, verbose_name='报工方式')),
                ('item_big_type', models.CharField(max_length=32, verbose_name='项目大类')),
                ('item_type', models.CharField(max_length=32, verbose_name='项目类型')),
                ('task_leader_no', models.CharField(max_length=32, verbose_name='任务负责人编号')),
                ('task_auditor_no', models.CharField(max_length=32, verbose_name='任务审核人编号')),
            ],
        ),
    ]
