# Generated by Django 4.0.5 on 2022-06-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_kq_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KQ_Task',
            new_name='KqTask',
        ),
    ]
